[build]
  functions = "netlify/functions"
  
[[redirects]]
  from = "/design-project"
  to = "/.netlify/functions/sendEmail/sendEmail"
  status = 200
  method = "POST"

[[headers]]
  for = "/*.css"
  [headers.values]
  Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
  Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
  Cache-Control = "public, max-age=31536000"
  